import time

def calculate_value(days,value):
    total_amount=days*value
    return total_amount
def question(answer):
    if ans.lower()=='yes':
        print('Your order is accepted. You have to take the car during 24 hours.')
        print('Thanks for choosing us.')
        exit(0)
    elif ans.lower()=='no':
        print('Your order is cancelled by you.')
        exit(0)
    else:
        print('This answer does not appear. Your order isn`t deleted.')
        print('The system is stopped.')
        exit(0)
name=input('Please enter your name:')
print('--------------------------------------------')
print(f'{name}, welcome to VIP Car Rental Center!')
while (True):
    print('''Car types:\n1-Small Cars\n2-Hybrid Cars\n3-Electric Cars\n4-SUV Cars\n5-4x4 Cars\n6-Estate Cars
7-Vans & Trucks\n8-Seater Cars\n9-Hatchback Cars\n10-Sport Cars''')
    print('--------------------------------------------')
    type_num=int(input('Please enter the number of the type of car which you want to rent:\n\n'))
    if type_num==1:
        print('Small, low cost, urban friendly, city cars. Designed to work and park with easy in tight spots.')
        print('''1-KIA PICANTO(15$ per day)\n2-NISSAN MICRA(13$ per day)\n3-HYUNDAI i10(14$ per day)
4-MITSUBISHI MIRAGE(17$ per day)\n5-MG3(18$ per day)\n6-VAUXHALL CORSA(19$ per day)\n\n''')
        num=int(input('Please enter the number of car which you want to rent:\n'))
        days=int(input('How many days do you want to rent?'))
        if num==1: print(f'KIA PICANTO for {days} days\n'+f'Total amount you should pay : {calculate_value(days,15)}$')
        elif num==2: print(f'NISSAN MICRA for {days} days\n'+f'Total amount you should pay : {calculate_value(days,13)}$')
        elif num==3: print(f'HYUNDAI i10 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,14)}$')
        elif num==4: print(f'MITSUBISHI MIRAGE for {days} days\n'+f'Total amount you should pay : {calculate_value(days,17)}$')
        elif num==5: print(f'MG3 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,18)}$')
        elif num==6: print(f'VAUXHALL CORSA for {days} days\n'+f'Total amount you should pay : {calculate_value(days,19)}$')
        else: 
            print('\nThis number does not belong to any car. Start again!')
            time.sleep(3)
            continue
        ans=input('\nDo you aggre with our politicy?(yes/no)')
        question(ans)
    if type_num==2:
        print('Improved emissions and running in Hybrid cars help keep more of your money in your pocket.')
        print('''1-KIA NIRO SELF-CHARGING(15$ per day)\n2-VAUXHALL GRANDLAND X HYBRID(22$ per day)\n3-HYUNDAI IONIQ HYBRID(10$ per day)
4-Honda Insight(18$ per day)\n5-Toyota Corolla(10$ per day)\n6-Honda Accord(20$ per day)\n7-Hyundai Sonata(23$ per day)\n\n''')
        num=int(input('Please enter the number of car which you want to rent:\n'))
        days=int(input('How many days do you want to rent?\n'))
        if num==1: print(f'KIA NIRO SELF-CHARGING for {days} days\n'+f'Total amount you should pay : {calculate_value(days,15)}$')
        elif num==2: print(f'VAUXHALL GRANDLAND X HYBRID for {days} days\n'+f'Total amount you should pay : {calculate_value(days,22)}$')
        elif num==3: print(f'HYUNDAI IONIQ HYBRID for {days} days\n'+f'Total amount you should pay : {calculate_value(days,10)}$')
        elif num==4: print(f'Honda Insight for {days} days\n'+f'Total amount you should pay : {calculate_value(days,18)}$')
        elif num==5: print(f'Toyota Corolla for {days} days\n'+f'Total amount you should pay : {calculate_value(days,10)}$')
        elif num==6: print(f'Honda Accord for {days} days\n'+f'Total amount you should pay : {calculate_value(days,20)}$')
        elif num==7: print(f'Hyundai Sonata for {days} days\n'+f'Total amount you should pay : {calculate_value(days,23)}$')
        else: 
            print('\nThis number does not belong to any car. Start again!')
            time.sleep(3)
            continue
        ans=input('\nDo you aggre with our politicy?(yes/no)\n')
        question(ans)
    if type_num==3:
        print('EVs are powered solely by electricity, completely eliminating your fuel bill and carbon emissions.')
        print('''1-NISSAN LEAF(10$ per day)\n2-MG5 EV(12$ per day)\n3-VAUXHALL MOKKA-e(30$ per day)
4-KIA EV6(25$ per day)\n5-KIA SOUL EV(23$ per day)\n6-NISSAN ARIYA(19$ per day)\n7-KIA e-NIRO(17$ per day)\n\n''')
        num=int(input('Please enter the number of car which you want to rent:\n'))
        days=int(input('How many days do you want to rent?\n\n'))
        if num==1: print(f'NISSAN LEAF for {days} days\n'+f'Total amount you should pay : {calculate_value(days,10)}$')
        elif num==2: print(f'MG5 EV for {days} days\n'+f'Total amount you should pay : {calculate_value(days,12)}$')
        elif num==3: print(f'VAUXHALL MOKKA-e for {days} days\n'+f'Total amount you should pay : {calculate_value(days,30)}$')
        elif num==4: print(f'KIA EV6 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,25)}$')
        elif num==5: print(f'KIA SOUL EV for {days} days\n'+f'Total amount you should pay : {calculate_value(days,23)}$')
        elif num==6: print(f'NISSAN ARIYA for {days} days\n'+f'Total amount you should pay : {calculate_value(days,19)}$')
        elif num==7: print(f'KIA e-NIRO for {days} days\n'+f'Total amount you should pay : {calculate_value(days,17)}$')
        else: 
            print('\nThis number does not belong to any car. Start again!')
            time.sleep(3)
            continue
        ans=input('\nDo you aggre with our politicy?(yes/no)\n')
        question(ans)
    if type_num==4:
        print('Combing the practicality of a family car with an SUV (sports utility vehicle) - often with off-roading capabilities.')
        print('''1-VAUXHALL MOKKA(33$ per day)\n2-MITSUBISHI SHOGUN SPORT(25$ per day)\n3-KIA SORENTO(19$ per day)
4-KIA SPORTAGE(27$ per day)\n5-HYUNDAI TUCSON(25$ per day)\n6-MITSUBISHI ECLIPSE(20$ per day)
7-VAUXHALL CROSSLAND X(15$ per day)\n8-VAUXHALL CROSSLAND(21$ per day)\n9-HYUNDAI TUCSON(19$ per day)\n\n''')
        num=int(input('Please enter the number of car which you want to rent:\n'))
        days=int(input('How many days do you want to rent?'))
        if num==1: print(f'VAUXHALL MOKKA for {days} days\n'+f'Total amount you should pay : {calculate_value(days,33)}$')
        elif num==2: print(f'MITSUBISHI SHOGUN SPORT for {days} days\n'+f'Total amount you should pay : {calculate_value(days,25)}$')
        elif num==3: print(f'KIA SORENTO for {days} days\n'+f'Total amount you should pay : {calculate_value(days,19)}$')
        elif num==4: print(f'KIA SPORTAGE for {days} days\n'+f'Total amount you should pay : {calculate_value(days,27)}$')
        elif num==5: print(f'HYUNDAI TUCSON for {days} days\n'+f'Total amount you should pay : {calculate_value(days,25)}$')
        elif num==6: print(f'MITSUBISHI ECLIPSE for {days} days\n'+f'Total amount you should pay : {calculate_value(days,20)}$')
        elif num==7: print(f'VAUXHALL CROSSLAND X for {days} days\n'+f'Total amount you should pay : {calculate_value(days,15)}$')
        elif num==8: print(f'VAUXHALL CROSSLAND for {days} days\n'+f'Total amount you should pay : {calculate_value(days,21)}$')
        elif num==9: print(f'HYUNDAI TUCSON for {days} days\n'+f'Total amount you should pay : {calculate_value(days,19)}$')
        else: 
            print('\nThis number does not belong to any car. Start again!')
            time.sleep(3)
            continue
        ans=input('\nDo you aggre with our politicy?(yes/no)\n')
        question(ans)
    if type_num==5:
        print("Don't just live life on the road, take your adventure off road with 4WD vehicles,\nenabling you to take your experience to the next level.")
        print('''1-NISSAN NAVARA(22$ per day)\n2-KIA SORENTO(20$ per day)\n3-MITSUBISHI SHOGUN SPORT(23$ per day)\n4-MITSUBISHI ASX(25$ per day)\n5-MITSUBISHI L200(19$ per day)\n\n''')
        num=int(input('Please enter the number of car which you want to rent:\n'))
        days=int(input('How many days do you want to rent?\n'))
        if num==1: print(f'NISSAN NAVARA for {days} days\n'+f'Total amount you should pay : {calculate_value(days,22)}$')
        elif num==2: print(f'KIA SORENTO for {days} days\n'+f'Total amount you should pay : {calculate_value(days,20)}$')
        elif num==3: print(f'MITSUBISHI SHOGUN SPORT for {days} days\n'+f'Total amount you should pay : {calculate_value(days,23)}$')
        elif num==4: print(f'MITSUBISHI ASX for {days} days\n'+f'Total amount you should pay : {calculate_value(days,25)}$')
        elif num==5: print(f'MITSUBISHI L200 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,19)}$')
        else: 
            print('\nThis number does not belong to any car. Start again!')
            time.sleep(3)
            continue
        ans=input('\nDo you aggre with our politicy?(yes/no)\n')
        question(ans)
    if type_num==6:
        print("Typically estate's are family hatchbacks but with a large rear extension on the back - giving large storage capacity.\n\n")
        print('''1-Kia Ceed Sportswagon(14$ per day)\n2-MG5(17$ per day)\n3-Kia ProCeed(15$ per day)\n\n\n''')
        num=int(input('Please enter the number of car which you want to rent:\n'))
        days=int(input('How many days do you want to rent?\n'))
        if num==1: print(f'Kia Ceed Sportswagon for {days} days\n'+f'Total amount you should pay : {calculate_value(days,14)}$')
        elif num==2: print(f'MG5 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,17)}$')
        elif num==3: print(f'Kia ProCeed for {days} days\n'+f'Total amount you should pay : {calculate_value(days,15)}$')
        else: 
            print('\nThis number does not belong to any car. Start again!')
            time.sleep(3)
            continue
        ans=input('\n\nDo you aggre with our politicy?(yes/no)\n')
        question(ans)
    if type_num==7:
        print('Vans come in all lengths, heights, and sizes - designed to suit your working environment perfectly.')
        print('''1-NISSAN NV250(15$ per day)\n2-NISSAN NV300(18$ per day)\n3-NISSAN NV400(22$ per day)\n4-VAUXHALL VIVARO LIFE(25$ per day)\n5-Chevrolet Colorado(17$ per day)
6-Dodge Ram 3500(22$ per day)\n7-Chevrolet Silverado 2500(19$ per day)\n\n''')
        num=int(input('Please enter the number of car which you want to rent:\n'))
        days=int(input('How many days do you want to rent?'))
        if num==1: print(f'NISSAN NV250 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,15)}$')
        elif num==2: print(f'NISSAN NV300 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,18)}$')
        elif num==3: print(f'NISSAN NV400 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,22)}$')
        elif num==4: print(f'VAUXHALL VIVARO LIFE for {days} days\n'+f'Total amount you should pay : {calculate_value(days,25)}$')
        elif num==5: print(f'Chevrolet Colorado for {days} days\n'+f'Total amount you should pay : {calculate_value(days,17)}$')
        elif num==6: print(f'Dodge Ram 3500 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,22)}$')
        elif num==7: print(f'Chevrolet Silverado 2500 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,19)}$')
        else: 
            print('\nThis number does not belong to any car. Start again!')
            time.sleep(3)
            continue
        ans=input('\n\n\nDo you aggre with our politicy?(yes/no)\n')
        question(ans)
    if type_num==8:
        print('Designed to be shared, 7 seater vehicles offer more room for your luggage and passengers.')
        print('''1-NISSAN X-TRAIL(18$ per day)\n2-HYUNDAI SANTA FE(16$ per day)\n3-MITSUBISHI SHOGUN SPORT(17$ per day)
4-KIA SORENTO(19$ per day)\n5-Land Rover Discovery(32$ per day)\n6-BMW X7(30$ per day)\n7-Audi Q7(29$ per day)
8-Citroen Grand C4 SpaceTourer(13$ per day)\n9-Peugeot 5008(27$ per day)\n\n\n''')
        num=int(input('Please enter the number of car which you want to rent:\n'))
        days=int(input('How many days do you want to rent?'))
        if num==1: print(f'NISSAN X-TRAIL for {days} days\n'+f'Total amount you should pay : {calculate_value(days,18)}$')
        elif num==2: print(f'HYUNDAI SANTA FE for {days} days\n'+f'Total amount you should pay : {calculate_value(days,16)}$')
        elif num==3: print(f'MITSUBISHI SHOGUN SPORT for {days} days\n'+f'Total amount you should pay : {calculate_value(days,17)}$')
        elif num==4: print(f'KIA SORENTO for {days} days\n'+f'Total amount you should pay : {calculate_value(days,19)}$')
        elif num==5: print(f'Land Rover Discovery for {days} days\n'+f'Total amount you should pay : {calculate_value(days,32)}$')
        elif num==6: print(f'BMW X7 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,30)}$')
        elif num==7: print(f'Audi Q7 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,29)}$')
        elif num==8: print(f'Citroen Grand C4 SpaceTourer for {days} days\n'+f'Total amount you should pay : {calculate_value(days,13)}$')
        elif num==9: print(f'Peugeot 5008 for {days} days\n'+f'Total amount you should pay : {calculate_value(days,27)}$')
        else: 
            print('\nThis number does not belong to any car. Start again!')
            time.sleep(3)
            continue
        ans=input('\n\n\nDo you aggre with our politicy?(yes/no)\n')
        question(ans)
    if type_num==9:
        print('Medium sized family hatchbacks cars, spacious enough for for extra passengers and luggage.')
        print('''1-KIA STONIC(20$ per day)\n2-VAUXHALL INSIGNIA(19$ per day)3-KIA CEED\n(14$ per day)
4-VAUXHALL CORSA(15$ per day)\n5-KIA RIO(15$ per day)\n6-NISSAN MICRA(10$ per day)\n7-MITSUBISHI MIRAGE(16$ per day)\n''')
        num=int(input('Please enter the number of car which you want to rent:\n'))
        days=int(input('How many days do you want to rent?'))
        if num==1: print(f'KIA STONIC for {days} days\n'+f'Total amount you should pay : {calculate_value(days,20)}$')
        elif num==2: print(f'VAUXHALL INSIGNIA for {days} days\n'+f'Total amount you should pay : {calculate_value(days,19)}$')
        elif num==3: print(f'KIA CEED for {days} days\n'+f'Total amount you should pay : {calculate_value(days,14)}$')
        elif num==4: print(f'VAUXHALL CORSA for {days} days\n'+f'Total amount you should pay : {calculate_value(days,15)}$')
        elif num==5: print(f'KIA RIO for {days} days\n'+f'Total amount you should pay : {calculate_value(days,15)}$')
        elif num==6: print(f'NISSAN MICRA for {days} days\n'+f'Total amount you should pay : {calculate_value(days,10)}$')
        elif num==7: print(f'MITSUBISHI MIRAGE for {days} days\n'+f'Total amount you should pay : {calculate_value(days,16)}$')
        else: 
            print('\nThis number does not belong to any car. Start again!')
            time.sleep(3)
            continue
        ans=input('\n\n\nDo you aggre with our politicy?(yes/no)\n')
        question(ans)
    if type_num==10:
        print('''The best sports cars come in all shapes, sizes, and prices.No matter your particular tastes,
we’re sure you can find something on this list of the best sports cars of 2021\nthat will fulfill your craving for speed and performance.''')
        print('''1-Mazda MX-5 Miata(900$ per day)\n2-Toyota Supra(1000$ per day)\n3-Chevy Corvette(2500$ per day)
4-Porsche 718 Cayman(1900$ per day)\n5-Porsche 718 Boxster(1200$ per day)\n6-BMW M2(500$ per day)\n7-Chevy Camaro(1400$ per day)
8-Ford Mustang(2100$ per day)\n9-BMW Z4(700$ per day)\n10-Mercedes-AMG GT(2400$ per day)
11-Porsche 911 Turbo(1950$ per day)\n12-Chevy Camaro ZL1(2600$ per day)\n\n\n''')
        num=int(input('Please enter the number of car which you want to rent:\n'))
        days=int(input('How many days do you want to rent?'))
        if num==1: print(f'Mazda MX-5 Miata for {days} days'+f'Total amount you should pay : {calculate_value(days,900)}$')
        elif num==2: print(f'Toyota Supra for {days} days'+f'Total amount you should pay : {calculate_value(days,1000)}$')
        elif num==3: print(f'Chevy Corvette for {days} days'+f'Total amount you should pay : {calculate_value(days,2500)}$')
        elif num==4: print(f'Porsche 718 Cayman for {days} days'+f'Total amount you should pay : {calculate_value(days,1900)}$')
        elif num==5: print(f'Porsche 718 Boxster for {days} days'+f'Total amount you should pay : {calculate_value(days,1200)}$')
        elif num==6: print(f'BMW M2 for {days} days'+f'Total amount you should pay : {calculate_value(days,500)}$')
        elif num==7: print(f'Chevy Camaro for {days} days'+f'Total amount you should pay : {calculate_value(days,1400)}$')
        elif num==8: print(f'Ford Mustang for {days} days'+f'Total amount you should pay : {calculate_value(days,2100)}$')
        elif num==9: print(f'BMW Z4 for {days} days'+f'Total amount you should pay : {calculate_value(days,700)}$')
        elif num==10: print(f'Mercedes-AMG GT for {days} days'+f'Total amount you should pay : {calculate_value(days,2400)}$')
        elif num==11: print(f'Porsche 911 Turbo for {days} days'+f'Total amount you should pay : {calculate_value(days,1950)}$')
        elif num==12: print(f'Chevy Camaro ZL1 for {days} days'+f'Total amount you should pay : {calculate_value(days,2600)}$')
        else: 
            print('\n\nThis number does not belong to any car. Start again!')
            time.sleep(3)
            continue
        ans=input('\n\n\n\nDo you aggre with our politicy?(yes/no)\n')
        question(ans)
